#!/bin/bash

# logbackup: backup rotated logfiles to s3.
# Copyright (C) 2016 Mario Finelli
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Get local configuration
source ~/.logbackup

for i in "${!LOGPATHS[@]}"; do
    logpath="${LOGPATHS[$i]}"
    for logfile in `ls $logpath`; do
        bucket_with_prefix=s3://"$BUCKET"/"${PREFIX[$i]}"/
        logs_in_bucket=`s3cmd ls "$bucket_with_prefix"`

        supposed_file="$(basename "$logfile").gpg"
        echo "$logs_in_bucket" | grep "$supposed_file" > /dev/null

        if [ $? -ne 0 ]; then
            echo "Need to create and upload $supposed_file"

            gpg --cipher-algo AES256 --symmetric --yes --batch \
                --passphrase="$PASSPHRASE" "$logfile"

            s3cmd put \
                --acl-private \
                --guess-mime-type \
                --server-side-encryption \
                "$supposed_file" \
                "${bucket_with_prefix}${supposed_file}"
        else
            echo "$supposed_file has already been uploaded to s3."
        fi
    done
done
